/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO SLIM 3
 */
public class AbsensiForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AbsensiForm.class.getName());
    private DefaultTableModel model;

    /**
     * Creates new form AbsensiForm
     */
    public AbsensiForm() {
        initComponents();
        isiDataAwal();
        model = (DefaultTableModel) tableAbsen.getModel();
        model.addColumn("Keterangan");
        tableAbsen.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihDataTabel();
            }
        });
    }
    
    private void pilihanDataTabel() {
        int baris = tableAbsen.getSelectedRow();
        if (baris != -1) {
            cmbNamaSiswa.setSelectedItem(model.getValueAt(baris, 0).toString());
            fieldTanggal.setText(model.getValueAt(baris, 1).toString());
            cmbStatus.setSelectedItem(model.getValueAt(baris, 2).toString());
            fieldKeterangan.setText(model.getValueAt(baris, 3).toString());
        }
    }
    
    private void bersihkan(){
        cmbNamaSiswa.setSelectedIndex(0);
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
        fieldTanggal.setText(sdf.format(new java.util.Date()));
        cmbStatus.setSelectedIndex(0);
        fieldKeterangan.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCatatAbsen = new javax.swing.JLabel();
        labelNamaSiswa = new javax.swing.JLabel();
        cmbNamaSiswa = new javax.swing.JComboBox<>();
        labelTanggal = new javax.swing.JLabel();
        fieldTanggal = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        labelKeterangan = new javax.swing.JLabel();
        fieldKeterangan = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAbsen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCatatAbsen.setText("Pencatatan Absen:");

        labelNamaSiswa.setText("Nama Siswa");

        cmbNamaSiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amelia Ulfa" }));

        labelTanggal.setText("Tanggal");

        labelStatus.setText("Status");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelKeterangan.setText("Keterangan");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);

        buttonUbah.setText("Ubah");

        buttonHapus.setText("Hapus");

        tableAbsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Tanggal", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableAbsen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonHapus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelKeterangan)
                                            .addComponent(labelStatus)
                                            .addComponent(labelTanggal)
                                            .addComponent(labelNamaSiswa)
                                            .addComponent(labelCatatAbsen))
                                        .addGap(93, 93, 93))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cmbNamaSiswa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldTanggal, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldKeterangan))
                                        .addGap(40, 40, 40)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUbah)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCatatAbsen)
                        .addGap(18, 18, 18)
                        .addComponent(labelNamaSiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelKeterangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHapus)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
    String nama = cmbNamaSiswa.getSelectedItem().toString();
    String tanggal = fieldTanggal.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();
    String keterangan = fieldKeterangan.getText().trim();

    if (tanggal.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tanggal tidak boleh kosong");
        return;
    }

    model.addRow(new Object[]{
        nama, tanggal, status, keterangan
    });

    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    bersihkan();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {
        int barisTerpilih = tableAbsen.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
    String nama = cmbNamaSiswa.getSelectedItem().toString();
    String tanggal = fieldTanggal.getText().trim();
    String status = cmbStatus.getSelectedItem().toString();
    String keterangan = fieldKeterangan.getText().trim();
    
    if (tanggal.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    model.setValueAt(nama, barisTerpilih, 0);
    model.setValueAt(tanggal, barisTerpilih, 1);
    model.setValueAt(status, barisTerpilih, 2);
    model.setValueAt(keterangan, barisTerpilih, 3);
    
    JOptionPane.showMessageDialog(this, "Data absen berhasil diubah!");
    bersihkan();

}

 private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {                                             
    int barisTerpilih = tableAbsen.getSelectedRow();
    if (barisTerpilih == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        model.removeRow(barisTerpilih);
        JOptionPane.showMessageDialog(this, "Data absen berhasil dihapus!");
        bersihkan();
    }
 }
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AbsensiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox<String> cmbNamaSiswa;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JTextField fieldKeterangan;
    private javax.swing.JTextField fieldTanggal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCatatAbsen;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JLabel labelNamaSiswa;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTable tableAbsen;
    // End of variables declaration//GEN-END:variables
}
