/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
/**
 *
 * @author LENOVO SLIM 3
 */
public class AbsensiForm extends javax.swing.JFrame {
    private DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AbsensiForm.class.getName());

    /**
     * Creates new form AbsensiForm
     */
    public AbsensiForm() {
        initComponents();
        
        setTitle("DATA ABSENSI");
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel)tableAbsen.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCatatAbsen = new javax.swing.JLabel();
        labelNamaSiswa = new javax.swing.JLabel();
        cmbNamaSiswa = new javax.swing.JComboBox<>();
        labelTanggal = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        labelKeterangan = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAbsen = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCatatAbsen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelCatatAbsen.setForeground(new java.awt.Color(255, 255, 255));
        labelCatatAbsen.setText("PENCATATAN ABSENKU");
        getContentPane().add(labelCatatAbsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        labelNamaSiswa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelNamaSiswa.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaSiswa.setText("Nama Siswa");
        getContentPane().add(labelNamaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        cmbNamaSiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Ahmad Fauzi", "Siti Aisyah", "Muhammad Rizky", "Nabila Putri", "Andi Saputra", "Dewi Lestari", "Fajar Ramadhan", "Nurul Hidayah", "Budi Santoso", "Rina Oktaviani", "Yoga Pratama", "Aulia Rahma", "Iqbal Maulana", "Putri Amelia", "Reza Akbar", "Annisa Zahra", "Dimas Nugraha", "Citra Maharani", "Arif Setiawan", "Nadya Safitri", "Rfi Hidayat", "Laila Fitriani", "Galang Prakoso", "Maya Prakoso", "Maya Salsabila", "Alvin Saputra", " ", " " }));
        getContentPane().add(cmbNamaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 151, -1));

        labelTanggal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        labelTanggal.setText("Tanggal");
        getContentPane().add(labelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        labelStatus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("Status");
        getContentPane().add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Sakit", "Izin ", "Alfa" }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 151, -1));

        labelKeterangan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelKeterangan.setForeground(new java.awt.Color(255, 255, 255));
        labelKeterangan.setText("Kelas");
        getContentPane().add(labelKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, 20));

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);
        getContentPane().add(buttonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, 30));

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(this::buttonUbahActionPerformed);
        getContentPane().add(buttonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 90, 30));

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(this::buttonHapusActionPerformed);
        getContentPane().add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 90, 30));

        tableAbsen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Tanggal", "Status", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAbsen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 300, 240));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "X IPA 1", "X IPA 2", "XI IPA 1", "XI IPA 2", "XII IPA 1", "XII IPA 2", " " }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 151, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Absensi.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
    String nama = cmbNamaSiswa.getSelectedItem().toString();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(jDateChooser1.getDate());
    String status = cmbStatus.getSelectedItem().toString();
    String kelas = jComboBox1.getSelectedItem().toString();

    model.addRow(new Object[]{
        nama,
        tanggal,
        status,
        kelas
    });

    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");

    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:String nama = cmbNamaSiswa.getSelectedItem().toString();

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(jDateChooser1.getDate());

    String status = cmbStatus.getSelectedItem().toString();
    String kelas = jComboBox1.getSelectedItem().toString();
    
    int baris = tableAbsen.getSelectedRow();

    if (baris != -1) {
        model.removeRow(baris);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus");
    }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
    int baris = tableAbsen.getSelectedRow();

    if (baris != -1) {

        model.setValueAt(cmbNamaSiswa.getSelectedItem().toString(), baris, 0);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        model.setValueAt(sdf.format(jDateChooser1.getDate()), baris, 1);

        model.setValueAt(cmbStatus.getSelectedItem().toString(), baris, 2);

        model.setValueAt(jComboBox1.getSelectedItem().toString(), baris, 3);

        JOptionPane.showMessageDialog(this, "Data berhasil diubah");

    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah");
    }
}   
    private void bersih() {
    cmbNamaSiswa.setSelectedIndex(0);
    cmbStatus.setSelectedIndex(0);
    jComboBox1.setSelectedIndex(0);
    jDateChooser1.setDate(null);
}

    private void tampilData() {


    }//GEN-LAST:event_buttonUbahActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AbsensiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox<String> cmbNamaSiswa;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCatatAbsen;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JLabel labelNamaSiswa;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTable tableAbsen;
    // End of variables declaration//GEN-END:variables
}
