/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO SLIM 3
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        
        setTitle("Beranda Utama");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelamatDatang = new javax.swing.JLabel();
        labelPilihMenu = new javax.swing.JLabel();
        buttonDataKelas = new javax.swing.JButton();
        buttonDataAbsensi = new javax.swing.JButton();
        buttonDataSiswa = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSelamatDatang.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        labelSelamatDatang.setText("SELAMAT DATANG DI PRESENSI ABSENKU");
        getContentPane().add(labelSelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 60));

        labelPilihMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelPilihMenu.setForeground(new java.awt.Color(255, 255, 255));
        labelPilihMenu.setText("PILIH MENU MANAJEMEN:");
        getContentPane().add(labelPilihMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 230, 50));

        buttonDataKelas.setBackground(new java.awt.Color(204, 51, 255));
        buttonDataKelas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonDataKelas.setText("DATA KELAS");
        buttonDataKelas.addActionListener(this::buttonDataKelasActionPerformed);
        getContentPane().add(buttonDataKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 150, 50));

        buttonDataAbsensi.setBackground(new java.awt.Color(255, 51, 51));
        buttonDataAbsensi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonDataAbsensi.setText("DATA ABSENSI");
        buttonDataAbsensi.addActionListener(this::buttonDataAbsensiActionPerformed);
        getContentPane().add(buttonDataAbsensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 170, 50));

        buttonDataSiswa.setBackground(new java.awt.Color(255, 102, 153));
        buttonDataSiswa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonDataSiswa.setText("DATA SISWA");
        buttonDataSiswa.addActionListener(this::buttonDataSiswaActionPerformed);
        getContentPane().add(buttonDataSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 170, 50));

        buttonLogout.setBackground(new java.awt.Color(102, 102, 255));
        buttonLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(this::buttonLogoutActionPerformed);
        getContentPane().add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1083, 730));
        jLabel1.setMinimumSize(new java.awt.Dimension(1083, 730));
        jLabel1.setPreferredSize(new java.awt.Dimension(1083, 730));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataKelasActionPerformed

    new KelasForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_buttonDataKelasActionPerformed

    private void buttonDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataSiswaActionPerformed

    new SiswaForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_buttonDataSiswaActionPerformed

    private void buttonDataAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataAbsensiActionPerformed
        new AbsensiForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonDataAbsensiActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed

    int jawab = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);

    if (jawab == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }

    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDataAbsensi;
    private javax.swing.JButton buttonDataKelas;
    private javax.swing.JButton buttonDataSiswa;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPilihMenu;
    private javax.swing.JLabel labelSelamatDatang;
    // End of variables declaration//GEN-END:variables
}
