/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;

/**
 *
 * @author LENOVO SLIM 3
 */
public class KelasForm extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelasForm.class.getName());

    
    /**
     * Creates new form KelasForm
     */
    public KelasForm() {
        initComponents();
        setLocationRelativeTo(null); // Tampil di tengah layar
        model = (DefaultTableModel) tableKelas.getModel(); // Hubungkan model tabel
        tableKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihData();
            }
        });
    
        pasangAksiTombol();
    }
    
     private void pasangAksiTombol() {
        buttonSimpan.addActionListener(evt -> buttonSimpanActionPerformed(evt));
        buttonUbah.addActionListener(evt -> buttonUbahActionPerformed(evt));
        buttonHapus.addActionListener(evt -> buttonHapusActionPerformed(evt));
        buttonBersih.addActionListener(evt -> buttonBersihActionPerformed(evt));
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInputData = new javax.swing.JLabel();
        labelIdKelas = new javax.swing.JLabel();
        fieldIdKelas = new javax.swing.JTextField();
        labelNamaKelas = new javax.swing.JLabel();
        fieldNamaKelas = new javax.swing.JTextField();
        labelAksi = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonBersih = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        labelInputData.setText("Input Data:");

        labelIdKelas.setText("ID Kelas");

        labelNamaKelas.setText("Nama Kelas");

        labelAksi.setText("Aksi:");

        buttonSimpan.setText("Simpan");

        buttonBersih.setText("Bersih");

        buttonUbah.setText("Ubah");

        buttonHapus.setText("Hapus");

        tableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Kelas", "Nama Kelas"
            }
        ));
        jScrollPane1.setViewportView(tableKelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAksi)
                    .addComponent(labelNamaKelas)
                    .addComponent(labelIdKelas)
                    .addComponent(labelInputData)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBersih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah))
                    .addComponent(fieldNamaKelas)
                    .addComponent(fieldIdKelas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInputData)
                        .addGap(23, 23, 23)
                        .addComponent(labelIdKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNamaKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAksi)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSimpan)
                            .addComponent(buttonUbah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBersih)
                            .addComponent(buttonHapus)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        
        String id = fieldIdKelas.getText().trim();
        String nama = fieldNamaKelas.getText().trim();

        if (id.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Kelas dan Nama Kelas tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equals(id)) {
                JOptionPane.showMessageDialog(this, "ID Kelas sudah ada!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        model.addRow(new Object[]{id, nama});
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        bersihkanInput();
    }     
    
     private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int baris = tableKelas.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id = fieldIdKelas.getText().trim();
        String nama = fieldNamaKelas.getText().trim();

        if (id.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        model.setValueAt(id, baris, 0);
        model.setValueAt(nama, baris, 1);
        
        JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        bersihkanInput();
    }  
     
    private void buttonHapusActionPerformed(ActionEvent evt) {                                             
        int baris = tableKelas.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data yang mau dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            model.removeRow(baris);
            JOptionPane.showMessageDialog(this, "Data dihapus!");
            bersihkanInput();
        }
    }      
    
    private void buttonBersihActionPerformed(ActionEvent evt) {                                             
        bersihkanInput();
    }

    private void pilihData() {
        int baris = tableKelas.getSelectedRow();
        if (baris != -1) {
            fieldIdKelas.setText(model.getValueAt(baris,0).toString());
            fieldNamaKelas.setText(model.getValueAt(baris,1).toString());
        }
    }
    
    private void bersihkanInput() {
        fieldIdKelas.setText("");
        fieldNamaKelas.setText("");
        fieldIdKelas.requestFocus();
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBersih;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JTextField fieldIdKelas;
    private javax.swing.JTextField fieldNamaKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAksi;
    private javax.swing.JLabel labelIdKelas;
    private javax.swing.JLabel labelInputData;
    private javax.swing.JLabel labelNamaKelas;
    private javax.swing.JTable tableKelas;
    // End of variables declaration//GEN-END:variables
}
