/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;
import java.sql.Connection;
import koneksi.koneksi;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO SLIM 3
 */
public class KelasForm extends javax.swing.JFrame {
    
    Connection conn;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelasForm.class.getName());

    /**
     * Creates new form KelasForm
     */
    public KelasForm() {
        initComponents();
        
        setTitle("Sistem Informasi Kelas");
        setLocationRelativeTo(null);
        
        conn = koneksi.getKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInputData = new javax.swing.JLabel();
        labelIdKelas = new javax.swing.JLabel();
        fieldIdKelas = new javax.swing.JTextField();
        labelNamaKelas = new javax.swing.JLabel();
        fieldNamaKelas = new javax.swing.JTextField();
        labelAksi = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        labelInputData.setText("Input Data:");

        labelIdKelas.setText("ID Kelas");

        labelNamaKelas.setText("Nama Kelas");

        labelAksi.setText("Aksi:");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(this::buttonUbahActionPerformed);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(this::buttonHapusActionPerformed);

        tableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Kelas", "Nama Kelas"
            }
        ));
        jScrollPane1.setViewportView(tableKelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAksi)
                    .addComponent(labelNamaKelas)
                    .addComponent(labelIdKelas)
                    .addComponent(labelInputData)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(buttonHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah))
                    .addComponent(fieldNamaKelas)
                    .addComponent(fieldIdKelas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInputData)
                        .addGap(23, 23, 23)
                        .addComponent(labelIdKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldIdKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNamaKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAksi)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSimpan)
                            .addComponent(buttonUbah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
    String sql = "INSERT INTO kelas(id_kelas,nama_kelas) VALUES (?,?)";

    try {
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, fieldIdKelas.getText());
        pst.setString(2, fieldNamaKelas.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

        tampilData();
        bersih();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}  
    private void bersih() {
    fieldIdKelas.setText("");
    fieldNamaKelas.setText("");
    }
    
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID Kelas");
    model.addColumn("Nama Kelas");

    try {

        String sql = "SELECT * FROM kelas";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while(rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_kelas"),
                rs.getString("nama_kelas")
            });

        }

        tableKelas.setModel(model);

    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        if(fieldIdKelas.getText().trim().isEmpty() ||
        fieldNamaKelas.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
            "ID Kelas dan Nama Kelas harus diisi!");
        return;
    }

    String sql = "UPDATE kelas SET nama_kelas=? WHERE id_kelas=?";

    try {

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, fieldNamaKelas.getText());
        pst.setInt(2, Integer.parseInt(fieldIdKelas.getText()));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
            "Data berhasil diubah");

        tampilData();
        bersih();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
    if(fieldIdKelas.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Pilih data yang akan dihapus!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

    if(konfirmasi == JOptionPane.YES_OPTION) {

        String sql = "DELETE FROM kelas WHERE id_kelas=?";

        try {

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1,
                Integer.parseInt(fieldIdKelas.getText()));

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                "Data berhasil dihapus");

            tampilData();
            bersih();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage());
        }
    }

    }//GEN-LAST:event_buttonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelasForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JTextField fieldIdKelas;
    private javax.swing.JTextField fieldNamaKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAksi;
    private javax.swing.JLabel labelIdKelas;
    private javax.swing.JLabel labelInputData;
    private javax.swing.JLabel labelNamaKelas;
    private javax.swing.JTable tableKelas;
    // End of variables declaration//GEN-END:variables
}
