/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO SLIM 3
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        setTitle("Login - Sistem Presensi Siswa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        textPresensi = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        labelLupaPassword = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textPresensi.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        textPresensi.setForeground(new java.awt.Color(255, 255, 255));
        textPresensi.setText("   PRESENSI SISWA");
        getContentPane().add(textPresensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 490, 190));
        getContentPane().add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 230, 30));
        getContentPane().add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 230, 30));

        labelUsername.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 230, -1));

        labelPassword.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 150, 30));

        buttonLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonLogin.setText("MASUK");
        buttonLogin.addActionListener(this::buttonLoginActionPerformed);
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 100, -1));

        labelLupaPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelLupaPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelLupaPassword.setText("Lupa Kata Sandi?");
        getContentPane().add(labelLupaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 130, 20));

        buttonLogout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buttonLogout.setText("KELUAR");
        buttonLogout.addActionListener(this::buttonLogoutActionPerformed);
        getContentPane().add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 100, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        String user = fieldUsername.getText();
        String pass = fieldPassword.getText();

        if(user.equals("TU") && pass.equals("TU26")){

            DashboardForm dashboard = new DashboardForm();
            dashboard.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(this,
                "Username atau Password salah!");
        }

    }//GEN-LAST:event_buttonLoginActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelLupaPassword;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel textPresensi;
    // End of variables declaration//GEN-END:variables
}
