/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package from;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author LENOVO SLIM 3
 */
public class SiswaForm extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SiswaForm.class.getName());

    /**
     * Creates new form SiswaForm
     */
    public SiswaForm() {
    initComponents();

    setTitle("Data Siswa");
    setLocationRelativeTo(null);

    model = (DefaultTableModel) tableSiswa.getModel();
    model.setRowCount(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        labelDataSiswa = new javax.swing.JLabel();
        labelNISN = new javax.swing.JLabel();
        fieldNISN = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        fieldNamaLengkap = new javax.swing.JTextField();
        labelKelas = new javax.swing.JLabel();
        cmbKelas = new javax.swing.JComboBox<>();
        buttonSimpan = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataSiswa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        labelDataSiswa.setText("INPUT DATA SISWA");
        getContentPane().add(labelDataSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        labelNISN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelNISN.setForeground(new java.awt.Color(255, 255, 255));
        labelNISN.setText("NISN/ID Siswa");
        getContentPane().add(labelNISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        getContentPane().add(fieldNISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 150, -1));

        labelNama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama Lengkap");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        getContentPane().add(fieldNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 150, -1));

        labelKelas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelKelas.setForeground(new java.awt.Color(255, 255, 255));
        labelKelas.setText("Kelas");
        getContentPane().add(labelKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "X IPA 1", "X IPA 2", "XI IPA 1", "XI IPA 2", "XII IPA 1", "XII IPA 2" }));
        getContentPane().add(cmbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, -1));

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(this::buttonSimpanActionPerformed);
        getContentPane().add(buttonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(this::buttonUbahActionPerformed);
        getContentPane().add(buttonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, -1));

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(this::buttonHapusActionPerformed);
        getContentPane().add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, -1));

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(this::buttonKembaliActionPerformed);
        getContentPane().add(buttonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NISN", "Nama Siswa", "Kelas"
            }
        ));
        jScrollPane1.setViewportView(tableSiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 370, 220));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Siswa.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed

    String nisn = fieldNISN.getText();
    String nama = fieldNamaLengkap.getText();
    String kelas = cmbKelas.getSelectedItem().toString();

    model.addRow(new Object[]{
        nisn,
        nama,
        kelas
    });

    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

    fieldNISN.setText("");
    fieldNamaLengkap.setText("");
    cmbKelas.setSelectedIndex(0);

    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed

    int baris = tableSiswa.getSelectedRow();

    if (baris != -1) {

        model.setValueAt(fieldNISN.getText(), baris, 0);
        model.setValueAt(fieldNamaLengkap.getText(), baris, 1);
        model.setValueAt(cmbKelas.getSelectedItem().toString(), baris, 2);

        JOptionPane.showMessageDialog(this, "Data berhasil diubah");

    } else {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu");
    }

    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
    int baris = tableSiswa.getSelectedRow();

    if (baris != -1) {
        model.removeRow(baris);
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
    }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        from.DashboardForm dashboard = new from.DashboardForm();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SiswaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JTextField fieldNISN;
    private javax.swing.JTextField fieldNamaLengkap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelDataSiswa;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelNISN;
    private javax.swing.JLabel labelNama;
    private javax.swing.JTable tableSiswa;
    // End of variables declaration//GEN-END:variables
}
